#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 12345
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: securitydb

#Server
ACTIVE_PROFILE: dev
SERVER_PORT: 9001

# Security Jwt Config
SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
EXPIRATION_JWT: 86400000
EXPIRATION__REFRESH_TOKEN: 604800000